W4D2/cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests, only: [:new, :create]

end

W4D2/cats/app/models/cat.rb
class Cat < ApplicationRecord
  validates :color, inclusion: { in: %w(White Black Yellow) }
  validates :sex, inclusion: { in: %w(M F) }
  validates :birth_date, :age, :color, :name, :sex, :description, presence: true

  has_many :rental_requests,
    class_name: :CatRentalRequest,
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy

end

W4D2/cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :status, inclusion: { in: %w(APPROVED DENIED) }
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validate :overlapping_approved_requests

  belongs_to :cat,
    class_name: :Cat,
    foreign_key: :cat_id,
    primary_key: :id

  private

  def overlapping_requests

  end

  def overlapping_approved_requests


  end

  def does_not_overlapping_approved_requests

  end

end

W4D2/cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

W4D2/cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestController < ApplicationController

  def new
    render :new

    # render json: "Hello"
  end


end

W4D2/cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])

    if @cat
      render :show
    else
      redirect_to cats_url
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cats_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end


  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :age, :sex, :color, :description)
  end


end

W4D2/cats/app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

W4D2/cats/app/helpers/cats_helper.rb
module CatsHelper
end

W4D2/cats/app/views/cats/_form.html.erb
<h1>
  <% if type == :new %>
      <%= "Make New Kitty" %>
      <% action_url = cats_url %>
  <% elsif type == :edit %>
      <%= "Edit your Kitty" %>
      <% action_url = cat_url(cat) %>
  <% end %>
</h1>


<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="cat_name">Kitty Name</label>
  <input id="cat_name" type="text" name="cat[name]" value="<%= cat.name %>"/>
  <br><br>

  <label for="birthday">Kitty Birthday</label>
  <input id="birthday" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>"/>
  <br><br>

  <label for="age">Kitty Age</label>
  <input id="age" type="text" name="cat[age]" value="<%= cat.age %>"/>
  <br><br>

  <label for="color">Kitty Color</label>
  <select id="color" name="cat[color]">
    <option disabled selected>--Choose color--</option>
    <option value="Black">Black</option>
    <option value="White">White</option>
    <option value="Yellow">Yellow</option>
  </select>
  <br><br>

  <label for="sex">Kitty Sex</label>
  <input type="radio" name="cat[sex]" value="M"/> Male
  <input type="radio" name="cat[sex]" value="F"> Female
  <br><br>

  <label for="description">Kitty Description</label><br>
  <textarea id = "description" name="cat[description]" value="<%= cat.description %>"></textarea>
  <br>

  <input type="submit" value="<%= type == :edit ? 'Make Kitty Better' : 'Make Kitty' %>">
</form>

<br>
<%= link_to 'Take me home', cats_url %>

W4D2/cats/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, type: :edit %>

W4D2/cats/app/views/cats/index.html.erb
<h1>All Cats</h1>

<ul>
  <% Cat.find_each do |cat| %>

    <li>
      <%= cat.name %>
      <%= link_to 'show cat', cat_url(cat) %>
    </li>
  <% end %>
</ul>


<%= link_to 'make kitty', new_cat_url %>

W4D2/cats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, type: :new %>

W4D2/cats/app/views/cats/show.html.erb
<h3>Cat's Info</h3>

<table>
  <tr>
    <th>Name</th>
    <th>Birthday</th>
    <th>Age</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.name %> </td>
    <td><%= @cat.birth_date %> </td>
    <td><%= @cat.age %> </td>
    <td><%= @cat.color %> </td>
    <td><%= @cat.sex %> </td>
    <td><%= @cat.description %> </td>
  </tr>
</table>

<%= button_to "Make Kitty Better", edit_cat_url(@cat), method: :get %>
<br>
<%= button_to 'Make Request', cat_rental_requests_url, method: :get %>
<%= link_to 'Take me home', cats_url %>